# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bonds',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='can_fly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.CharField(choices=[(b'Alchemist', b'Alchemist'), (b'Alert', b'Alert'), (b'Athlete', b'Athlete'), (b'Actor', b'Actor'), (b'Blade Mastery', b'Blade Mastery'), (b'Burglar', b'Burglar'), (b'Charger', b'Charger'), (b'Crossbow Expert', b'Crossbow Expert'), (b'Defensive Duelist', b'Defensive Duelist'), (b'Dual Wielder', b'Dual Wielder'), (b'Dungeon Delver', b'Dungeon Delver'), (b'Durable', b'Durable'), (b'Elemental Adept', b'Elemental Adept'), (b'Fell Handed', b'Fell Handed'), (b'Flail Mastery', b'Flail Mastery'), (b'Grappler', b'Grappler'), (b'Gourmand', b'Gourmand'), (b'Great Weapon Master', b'Great Weapon Master'), (b'Healer', b'Healer'), (b'Heavily Armoured', b'Heavily Armoured'), (b'Heavy Armour Master', b'Heavy Armour Master'), (b'Inspiring Leader', b'Inspiring Leader'), (b'Keen Mind', b'Keen Mind'), (b'Lightly Armoured', b'Lightly Armoured'), (b'Linguist', b'Linguist'), (b'Lucky', b'Lucky'), (b'Mage Slayer', b'Mage Slayer'), (b'Magic Initiate', b'Magic Initiate'), (b'Martial Adept', b'Martial Adept'), (b'Master of Disguise', b'Master of Disguise'), (b'Medium Armour Master', b'Medium Armour Master'), (b'Mobile', b'Mobile'), (b'Moderately Armoured', b'Moderately Armoured'), (b'Mounted Combatant', b'Mounted Combatant'), (b'Observant', b'Observant'), (b'Polearm Master', b'Polearm Master'), (b'Resilient', b'Resilient'), (b'Ritual Caster', b'Ritual Caster'), (b'Savage Attacker', b'Savage Attacker'), (b'Sentinel', b'Sentinel'), (b'Sharpshooter', b'Sharpshooter'), (b'Shield Master', b'Shield Master'), (b'Skilled', b'Skilled'), (b'Skulker', b'Skulker'), (b'Spear Mastery', b'Spear Mastery'), (b'Spell Sniper', b'Spell Sniper'), (b'Svirfneblin Magic', b'Svirfneblin Magic'), (b'Tavern Brawler', b'Tavern Brawler'), (b'Tough', b'Tough'), (b'War Caster', b'War Caster'), (b'Weapon Master', b'Weapon Master')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='flaws',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='ideals',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='movement',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='character',
            name='p_traits',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True, default=21, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.IntegerField(blank=True, default=192, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug_id',
            field=models.CharField(default='i0lSX8pmiBpP', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='subrace',
            field=models.CharField(choices=[(b'Gavony Human', b'Gavony Human'), (b'Kessig Human', b'Kessig Human'), (b'Nephalia Human', b'Nephalia Human'), (b'Stensia Human', b'Stensia Human'), (b'Emeria Merfolk', b'Emeria Merfolk'), (b'Ula Merfolk', b'Ula Merfolk'), (b'Cosi Merfolk', b'Cosi Merfolk'), (b'Grotag Goblin', b'Grotag Goblin'), (b'Lavastep Goblin', b'Lavastep Goblin'), (b'Tuktuk Goblin', b'Tuktuk Goblin'), (b'Protector', b'Aasimar Protector'), (b'Scourge', b'Aasimar Scourge'), (b'Fallen', b'Fallen Aasimar'), (b'Beasthide', b'Beasthide Shifter'), (b'Cliffwalk', b'Cliffwalk Shifter'), (b'Longstride', b'Longstride Shifter'), (b'Longtooth', b'Longtooth Shifter'), (b'Razorclaw', b'Razorclaw Shifter'), (b'Wildhunt', b'Wildhunt Shifter'), (b'Windsoul', b'Air Genasi'), (b'Earthsoul', b'Earth Genasi'), (b'Watersoul', b'Water Genasi'), (b'Firesoul', b'Fire Genasi'), (b'Joraga', b'Joraga'), (b'Tajuru', b'Tajuru'), (b'Mul Daya', b'Mul Daya'), (b'Human Revenant', b'Human Revenant'), (b'Tiefling Revenant', b'Tiefling Revenant'), (b'Abyssal Tiefling', b'Abyssal Tiefling'), (b'Dragonborn Revenant', b'Dragonborn Revenant'), (b'Minotaur', b'Minotaur'), (b'Kor', b'Kor'), (b'Vampire', b'Vampire'), (b'Bugbear', b'Bugbear'), (b'Kenku', b'Kenku'), (b'Kobold', b'Kobold'), (b'Tabaxi', b'Tabaxi'), (b'Triton', b'Triton'), (b'Warforged', b'Warforged'), (b'Yuan-ti Pureblood', b'Yuan-Ti Pureblood'), (b'Aarakocra', b'Aarakocra'), (b'Lizardfolk', b'Lizardfolk'), (b'Hobgoblin', b'Hobgoblin'), (b'Goliath', b'Goliath'), (b'Firbolg', b'Firbolg'), (b'Dragonborn', b'Dragonborn'), (b'Mountain Dwarf', b'Mountain Dwarf'), (b'Human Variant', b'Human Variant'), (b'Half-Elf', b'Half-Elf'), (b'Half-Wood Elf', b'Half-Wood Elf'), (b'Half-Moon Elf', b'Half-Moon Elf'), (b'Half-Sun Elf', b'Half-Sun Elf'), (b'Half-Drow', b'Half-Drow Elf'), (b'Half-Aquatic Elf', b'Half-Aquatic Elf'), (b'Tiefling', b'Tiefling'), (b'Feral Tiefling', b'Feral Tiefling'), (b'Half-Orc', b'Half-Orc'), (b'Forest Gnome', b'Forest Gnome'), (b'Human', b'Human'), (b'Rock Gnome', b'Rock Gnome'), (b'Deep Gnome', b'Deep Gnome'), (b'Hill Dwarf', b'Hill Dwarf'), (b'Duergar', b'Duergar'), (b'High Elf', b'High Elf'), (b'Wood Elf', b'Wood Elf'), (b'Drow', b'Drow'), (b'Eladrin', b'Eladrin'), (b'Ghostwise Halfling', b'Ghostwise Halfling'), (b'Lightfoot Halfling', b'Lightfoot Halfling'), (b'Stout Halfling', b'Stout Halfling')], max_length=25),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.IntegerField(blank=True, default=200, null=True),
        ),
    ]
