# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20170309_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat', models.CharField(choices=[(b'Alchemist', b'Alchemist'), (b'Alert', b'Alert'), (b'Athlete', b'Athlete'), (b'Actor', b'Actor'), (b'Blade Mastery', b'Blade Mastery'), (b'Burglar', b'Burglar'), (b'Charger', b'Charger'), (b'Crossbow Expert', b'Crossbow Expert'), (b'Defensive Duelist', b'Defensive Duelist'), (b'Dual Wielder', b'Dual Wielder'), (b'Dungeon Delver', b'Dungeon Delver'), (b'Durable', b'Durable'), (b'Elemental Adept', b'Elemental Adept'), (b'Fell Handed', b'Fell Handed'), (b'Flail Mastery', b'Flail Mastery'), (b'Grappler', b'Grappler'), (b'Gourmand', b'Gourmand'), (b'Great Weapon Master', b'Great Weapon Master'), (b'Healer', b'Healer'), (b'Heavily Armoured', b'Heavily Armoured'), (b'Heavy Armour Master', b'Heavy Armour Master'), (b'Inspiring Leader', b'Inspiring Leader'), (b'Keen Mind', b'Keen Mind'), (b'Lightly Armoured', b'Lightly Armoured'), (b'Linguist', b'Linguist'), (b'Lucky', b'Lucky'), (b'Mage Slayer', b'Mage Slayer'), (b'Magic Initiate', b'Magic Initiate'), (b'Martial Adept', b'Martial Adept'), (b'Master of Disguise', b'Master of Disguise'), (b'Medium Armour Master', b'Medium Armour Master'), (b'Mobile', b'Mobile'), (b'Moderately Armoured', b'Moderately Armoured'), (b'Mounted Combatant', b'Mounted Combatant'), (b'Observant', b'Observant'), (b'Polearm Master', b'Polearm Master'), (b'Resilient', b'Resilient'), (b'Ritual Caster', b'Ritual Caster'), (b'Savage Attacker', b'Savage Attacker'), (b'Sentinel', b'Sentinel'), (b'Sharpshooter', b'Sharpshooter'), (b'Shield Master', b'Shield Master'), (b'Skilled', b'Skilled'), (b'Skulker', b'Skulker'), (b'Spear Mastery', b'Spear Mastery'), (b'Spell Sniper', b'Spell Sniper'), (b'Svirfneblin Magic', b'Svirfneblin Magic'), (b'Tavern Brawler', b'Tavern Brawler'), (b'Tough', b'Tough'), (b'War Caster', b'War Caster'), (b'Weapon Master', b'Weapon Master')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'feat',
                'verbose_name_plural': 'feats',
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='feats',
        ),
        migrations.AlterField(
            model_name='character',
            name='slug_id',
            field=models.CharField(default='5BJhlHtVUwwd', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(blank=True, to='character.Feats', verbose_name='feats'),
        ),
    ]
