# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20170309_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='feats',
            name='effect',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug_id',
            field=models.CharField(default='Iy1ycqqYkQRq', max_length=12, primary_key=True, serialize=False),
        ),
    ]
